import { useEffect, useState } from 'react'
import { BrainCircuit, ChartNoAxesColumnIncreasing, Target } from 'lucide-react'
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/Card'
import { Badge } from '@/components/ui/Badge'
import { StatCard } from '@/components/ui/StatCard'
import { api } from '@/lib/api'

export default function Analytics() {
  const [data, setData] = useState<any>(null)
  useEffect(() => { api.analytics().then(setData).catch(() => undefined) }, [])
  const m = data?.model
  return <div className="space-y-6"><div><Badge tone="green">MODEL ANALYTICS</Badge><h1 className="mt-3 text-3xl font-semibold tracking-tight">Know what the model knows.</h1><p className="mt-2 max-w-2xl text-sm text-white/40">Validation metrics and feature importance make the ML portion of SmartEV transparent for demos, reports and viva questions.</p></div><div className="grid gap-4 sm:grid-cols-3"><StatCard label="R²" value={m ? m.r2.toFixed(3) : '—'} detail="held-out test set" icon={<Target size={18}/>} accent="green"/><StatCard label="MAE" value={m ? m.mae.toFixed(3) : '—'} detail="km/kWh" icon={<BrainCircuit size={18}/>} accent="blue"/><StatCard label="RMSE" value={m ? m.rmse.toFixed(3) : '—'} detail="km/kWh" icon={<ChartNoAxesColumnIncreasing size={18}/>} accent="red"/></div><div className="grid gap-5 xl:grid-cols-2"><Card><CardHeader><CardTitle>Feature importance</CardTitle><p className="mt-1 text-xs text-white/30">Permutation importance on a deterministic sample.</p></CardHeader><CardContent><div className="h-[340px] pt-5">{data && <ResponsiveContainer width="100%" height="100%"><BarChart data={data.feature_importance} layout="vertical" margin={{left:20,right:10}}><CartesianGrid stroke="#ffffff08" horizontal={false}/><XAxis type="number" stroke="#ffffff30" tickLine={false} axisLine={false} fontSize={10}/><YAxis dataKey="feature" type="category" width={115} stroke="#ffffff40" tickLine={false} axisLine={false} fontSize={10}/><Tooltip contentStyle={{background:'#11141b',border:'1px solid #ffffff12',borderRadius:12}}/><Bar dataKey="importance" fill="#ef4444" radius={[0,5,5,0]}/></BarChart></ResponsiveContainer>}</div></CardContent></Card><Card><CardHeader><CardTitle>Average efficiency by vehicle class</CardTitle></CardHeader><CardContent><div className="h-[340px] pt-5">{data && <ResponsiveContainer width="100%" height="100%"><BarChart data={data.class_efficiency}><CartesianGrid stroke="#ffffff08" vertical={false}/><XAxis dataKey="Vehicle class" stroke="#ffffff35" tickLine={false} axisLine={false} fontSize={9} angle={-20} textAnchor="end" height={65}/><YAxis stroke="#ffffff35" tickLine={false} axisLine={false} fontSize={10}/><Tooltip contentStyle={{background:'#11141b',border:'1px solid #ffffff12',borderRadius:12}}/><Bar dataKey="efficiency" fill="#38bdf8" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer>}</div></CardContent></Card></div></div>
}
